- name: solution-submission
  color: "00ff00"
  description: "A new solution submission for a question."

- name: bug
  color: "ff0000"
  description: "Something isn't working."

- name: enhancement
  color: "00bfff"
  description: "New feature or request."

- name: documentation
  color: "4169e1"
  description: "Improvements or additions to documentation."

- name: help wanted
  color: "14b8a6"
  description: "Extra attention is needed."

- name: question
  color: "8b5cf6"
  description: "Further information is requested."

- name: review needed
  color: "ffd700"
  description: "Needs review by maintainers."

- name: good first issue
  color: "9370db"
  description: "Good for newcomers."

- name: discussion
  color: "a9a9a9"
  description: "Open for discussion."

- name: duplicate
  color: "808080"
  description: "This issue or pull request already exists."

- name: invalid
  color: "ffff00"
  description: "This doesn't seem right."

- name: wontfix
  color: "ffffff"
  description: "This will not be worked on."

- name: badge-eligible
  color: "ff8c00"
  description: "This PR/issue is eligible for a badge."

- name: weekly-challenge
  color: "ff1493"
  description: "Weekly challenge submissions and discussions."

- name: solutions
  color: "32cd32"
  description: "Changes to solution files."

- name: workflows
  color: "9932cc"
  description: "Changes to GitHub Actions workflows."

- name: config
  color: "ffa500"
  description: "Changes to configuration files."

- name: questions
  color: "ff4500"
  description: "Changes to question files."

- name: python
  color: "3776ab"
  description: "Changes to Python code files."

- name: templates
  color: "f0e68c"
  description: "Changes to template files."
