name: 🤖 All Contributors Bot

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [closed]

jobs:
  all-contributors:
    runs-on: ubuntu-latest
    steps:
      - name: All Contributors Action
        uses: all-contributors/all-contributors-action@v6.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
