name: 🤖 All Contributors Bot

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [closed]

permissions:
  contents: write
  pull-requests: read
  issues: read

jobs:
  all-contributors:
    runs-on: ubuntu-latest
    steps:
      - name: All Contributors Action
        uses: all-contributors/all-contributors-action@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
