name: 🤖 Auto Assign Reviewer

on:
  pull_request:
    types: [opened, ready_for_review]

permissions:
  pull-requests: write

jobs:
  add-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Assign default reviewer
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              reviewers: ['mayankpriy']
            });
