name: 🤖 Welcome Bot

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: 🤝 Welcome new contributors
        uses: actions/github-script@v7
        with:
          script: |
            const { data: issue } = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            const isNewContributor = issue.author_association === 'FIRST_TIME_CONTRIBUTOR';

            if (isNewContributor) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: "🎉 Welcome to Python Atelier! 🎨\n\nCheck out our [Solution Guidelines](SOLUTION_GUIDELINES.md) and [Contributing Guide](CONTRIBUTING.md) to get started!\n\nHappy coding! 🚀✨"
              });
            }

            // Add labels
            if (context.eventName === 'issues') {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: ['community']
              });
            } else if (context.eventName === 'pull_request') {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: ['solution-submission']
              });
            }
